title: Paul Thielen # your name (or website title) here
logo: "/images/profile_image_new.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have a strong foundation in Data Science, with a focus on statistics and machine learning. Previously worked as a Data Analyst Intern at Uber, 
  focusing on analytical work and gaining practical experience in data-driven decision-making.
  <br><br>
  Starting January 2026, I will begin my MS in ECE AIML at CMU to deepen my expertise in AI and machine learning, with the goal of becoming a 
  Research Scientist focused on developing adaptable, resilient, and trustworthy AI systems for medical devices
  <br><br>
  <a href="https://www.linkedin.com/in/paul-thielen/">View My LinkedIn Profile</a>
  <br>
  <a href=" https://scholar.google.com/citations?user=LfLiUPUAAAAJ&hl=en&oi=ao">View My Google Scholar Profile</a> 
 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: GT-MK4TRV8D # your Google Analytics tracking ID here
